language: rust

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - mingw-w64
      - upx
      - musl
      - musl-dev
      - musl-tools
env:
matrix:
  allow_failures:
    - rust: nightly
  include:
    - env:
      - TARGET=x86_64-unknown-linux-musl
      - BIN_NAME=cli
      - PROPER_NAME=fints-institute-db-linux
      os: linux
      rust: stable
    - env:
      - TARGET=x86_64-pc-windows-gnu
      - BIN_NAME=cli.exe
      - PROPER_NAME=fints-institute-db-win.exe
      - RUSTFLAGS="-C linker=x86_64-w64-mingw32-gcc"
      os: linux
      rust: stable
    - env:
      - TARGET=x86_64-apple-darwin
      - BIN_NAME=cli
      - PROPER_NAME=fints-institute-db-osx
      os: osx
      rust: stable

before_install:
  - rustup self update

install:
  # On Apple, the default target is already the right one.
  - if [[ -n $TARGET && $TARGET != "x86_64-apple-darwin" ]]; then rustup target add $TARGET; fi

script:
  # If this is a normal, non-deployment build...
  - if [[ -z $TARGET ]]; then cargo build --verbose; fi
  - if [[ -n $TARGET ]]; then cargo build --verbose --release --target $TARGET; fi

before_deploy:
  # If this is a binary deployment...
  - if [[ -n $TARGET ]]; then cp -a target/$TARGET/release/$BIN_NAME $PROPER_NAME && strip $PROPER_NAME; fi
  - # Run upx on the binary if this is a deployment for Linux or Windows
  - if [[ $TARGET = "x86_64-pc-windows-gnu" ]]; then upx $PROPER_NAME; fi
  - if [[ $TARGET = "x86_64-unknown-linux-musl" ]]; then upx $PROPER_NAME; fi

deploy:
  - provider: releases
    api_key:
      secure: "kD58uWu2jvSdeG2RfWnkXHFRAA8zV96uz0wgqXfmYITw0JK5izAdpCUvK82dEfH7hHnV+6emVUPtnINzLRZwJE8rTnJPUIuAYTE6eP+uG7j5WVYy7+pVzn/i2X8wGGtcTzvMZTqpS41SouuVcpzkYlzsGcBxS1+vtFSmrU9BE5io6uL86Q4cfY/9HeIPSL3KVsvDooDTMpsJOftsJ8hDafJi6oGVxw9/WpWrNgy7zNXjac8oVH1EpfGi0RKyPGTms3zoEjwtG8acKR0EFX6ITW86aHlS+uuy+3MIxtjxN48E5/oErjsrT0TNXyJWH0zg+VsmMszeXFkvZ9tTHVmhqmMIcdDQgTaPBZnZdevY0qFXMMNjYCS6aWjz8d93hFgbjc6jIKj32KFEfENfPIn66eeNi5NcPnHlISmgMlhypMjsJ8JOue1PqJVL72aWZeGKdNs8XR82QH7bJYum40NmGMG6SD2WHFUR0RZ2RoROeI6UEvnEU/jrmJ08NCyA9f4pPsGR3ejcO5fgKTf5s3sM/LXMeqc9CYLUTOlk46JfoSWJoOlBNRB7CCN7sQjQ+68M3sOYlY5fGAR4S/TwNR+Hzv9aumnU5DOxjrpojauOkWFdOXNrnieCSu0tKRhb6Qx1fBtIH3IW+2Cb282L1pAcaiqjyIcQMDcf/jb3P2ECSlg="
    file: $PROPER_NAME
    skip_cleanup: true
    on:
      branch: master
      tags: true
      condition: $TRAVIS_RUST_VERSION = stable && -n $TARGET
