language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - mingw-w64
      - upx
      - musl
      - musl-dev
      - musl-tools
env:
matrix:
  allow_failures:
    - rust: stable
  include:
    - env:
      - TARGET=x86_64-unknown-linux-musl
      - BIN_NAME=fints-institute-db
      - PROPER_NAME=fints-institute-db-linux
      os: linux
      rust: nightly
    - env:
      - TARGET=x86_64-pc-windows-gnu
      - BIN_NAME=fints-institute-db.exe
      - PROPER_NAME=fints-institute-db-win.exe
      - RUSTFLAGS="-C linker=x86_64-w64-mingw32-gcc"
      os: linux
      rust: nightly
    - env:
      - TARGET=x86_64-apple-darwin
      - BIN_NAME=fints-institute-db
      - PROPER_NAME=fints-institute-db-osx
      os: osx
      rust: nightly

before_install:
  - rustup self update

install:
  # On Apple, the default target is already the right one.
  - if [[ -n $TARGET && $TARGET != "x86_64-apple-darwin" ]]; then rustup target add $TARGET; fi

script:
  # If this is a normal, non-deployment build...
  - if [[ -z $TARGET ]]; then cargo build --verbose; fi
  - if [[ -n $TARGET ]]; then cargo build --verbose --release --target $TARGET; fi

before_deploy:
  # If this is a binary deployment...
  - if [[ -n $TARGET ]]; then cp -a target/$TARGET/release/$BIN_NAME $PROPER_NAME && strip $PROPER_NAME; fi
  - # Run upx on the binary if this is a deployment for Linux or Windows
  - if [[ $TARGET = "x86_64-pc-windows-gnu" ]]; then upx $PROPER_NAME; fi
  - if [[ $TARGET = "x86_64-unknown-linux-musl" ]]; then upx $PROPER_NAME; fi

deploy:
  - provider: releases
    api_key:
      secure: "pMLbOIQ2HM5xCT1hcTkQAAKmQ6lLAIqLIcYAHMn0TZ/iAC9B7BTisaSqC5k6IdlywqFcB5Tp1xYZ8SOx0+pjg8pikCsZaRdTIvfSF5W6okXNoCEwssDSkG7eQ1loJYsjb4b7FTRSrQzkPoFNO2K6B10xVl/Ga6OgIEoSD0YZT1ZByym/Ab5Mb11a9GhG/42PMilHZGBp+NZ1qOcAFk6b9IPzNd7SdJfYMBMLdFj8LOKK68hIIcWJDZG1W2th7Z7ynLUADZ4BP39xIRslSEA4bny0xDzXpir3MAgXNdkj66ypLhoB/utLQs+OXf8IoU3ihLjO75/q1yvJqX+gGbFKAWGkAXwHzxC07WoT5KFOP26nnxJ3+BWlq72+gFVCRtxgvLMcSvQtThk/wOxIj7mmzaP6eNK9WRjgr8oR7Uf78v2s4i0RwxjD0A2HwCZHLxzp4bOMJl2I+vAyfDoODQMLMee2vGtpnZrLwe4s8KE4LXM29R6TkC0Qek1vTLcfaY1lj7O7eehRwzkFO7yzphq/KOBK8cLwS5OKkcUdeVgcA/JzgjlCzEpFr8gW2m4T/R47iu2p5/8nhUDoZLNmhd394kyINAYEYExR0Rm53FMp1o0hEvV+5b+2kcuoJpm7WQLA0L3UVXI9gtkUeAz4W85QqX9gi5rGQLziXyn7QE3TkbU="
    file: $PROPER_NAME
    skip_cleanup: true
    on:
      branch: master
      tags: true
      condition: $TRAVIS_RUST_VERSION = nightly && -n $TARGET
