[package]
name = "fints-institute-db"
version = "0.1.0"
authors = ["Sven-Hendrik Haase <svenstaro@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1"
clap = "2"
iban_validate = "1"
chrono = { version = "0.4", features = ["serde"] }
serde = "1"
serde_derive = "1"
serde_json = "1"

[build-dependencies]
reqwest = "0.9"
encoding_rs = "0.8"
